stages:
  - quality
  - build

default:
  image: node:20-alpine
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - .next/cache/

lint:
  stage: quality
  before_script:
    - npm ci --prefer-offline --no-audit
  script:
    - npx next lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

typecheck:
  stage: quality
  before_script:
    - npm ci --prefer-offline --no-audit
  script:
    - npx tsc --noEmit
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build:
  stage: build
  before_script:
    - npm ci --prefer-offline --no-audit
  script:
    - npx prisma generate
    - npm run build
  artifacts:
    paths:
      - .next/
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
